version: '3.8'
services:
  db:
    image: mysql:latest
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: 512M
    container_name: products_api
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: products_api

    volumes:
      - /docker/hibernate-poc:/var/lib/mysql
